# Maintainer: Gunther Schulz <dev@guntherschulz.de>

pkgname=cursor-bin
pkgver=1.4.2
pkgrel=2
pkgdesc='AI-first coding environment'
arch=('x86_64')
url="https://www.cursor.com"
license=('LicenseRef-Cursor_EULA')
depends=('ripgrep' 'xdg-utils'
  'gcc-libs' 'hicolor-icon-theme' 'libxkbfile' 'electron28')
options=(!strip) # Don't break ext of VSCode
_appimage="${pkgname}-${pkgver}.AppImage"
_commit=150823e9ded15fddfd743c7122b4724130c25df8
source=("${_appimage}::https://downloads.cursor.com/production/150823e9ded15fddfd743c7122b4724130c25df8/linux/x64/Cursor-1.4.2-x86_64.AppImage")
sha512sums=('06eaaea9c9b4be407a73c8839ba8a9bbb19020a0bb39e36b84e721a112dfaeabe543314e2cd6e2a11a1c75fb0d6420a02f690bba6a4f438ca7dd1a98296cbf7f')
  # Extract Electron version from depends array BEFORE changing directories

  rm -rf squashfs-root
  chmod +x ${_appimage}
  # Don't use upstream's broken resources
  for _f in co.anysphere.cursor.png usr/bin usr/share/{appdata,applications,bash-completion,mime,zsh}
    do ./${_appimage} --appimage-extract $_f > /dev/null
  done
  ./${_appimage} --appimage-extract usr/share/cursor/resources/app > /dev/null
  cd squashfs-root
  mv usr/share/zsh/{vendor-completions,site-functions}
  install -Dm644 co.anysphere.cursor.png -t usr/share/pixmaps
  ln -svf /usr/bin/rg ${_app}/node_modules/@vscode/ripgrep/bin/rg
  ln -svf /usr/bin/xdg-open ${_app}/node_modules/open/xdg-open

  mv usr "${pkgdir}"/usr

  # Install the pre-generated cursor.sh script
  # This file is created by update_pkgbuild.py during the update process
  if [ -f "${srcdir}/cursor.sh" ]; then
      install -Dm755 "${srcdir}/cursor.sh" "${pkgdir}"/usr/share/cursor/cursor
      echo "cursor.sh installed successfully"
  else
      echo "ERROR: cursor.sh not found. This file should be generated by update_pkgbuild.py"
      exit 1
  fi
}
